### ISSUE TITLE
flag joke

### ISSUE THREAD

**Issue by jamesjsewell** [Sv443/JokeAPI#288] opened 2021-05-31 05:04 UTC
## The joke's ID:
177

## Why the joke should be removed / reflagged / recategorized:
this is a racist joke and should be flagged as such

## Alternative to the joke:
dont have one

**Comment by Sv443** [comment] 2021-05-31 10:06
How is this joke racist? It's not discriminating against anything, it's just making a pun based on the Spanish language.

**Comment by jamesjsewell** [comment] 2021-05-31 15:57
I guess it's not a malicious joke but I was hoping that the "racist" flag would exclude any joke that mentions race. It really depends on who you ask, something that's not offensive to you may offend others.

**Comment by Sv443** [comment] 2021-06-01 19:02
Yeah sadly I can't cater to everyone's tolerance level. The flags are more intended for negative stuff, and additionally the `racist` flag was intended for direct racism.
I'm gonna recategorize the joke from your other issue but I will close this issue.
Thanks for contributing!

**Closed by Sv443** 2021-06-01 19:02 UTC
